### ISSUE TITLE
SSL error 

### ISSUE THREAD

**Issue by lgatto** [carpentries-incubator/bioc-intro#109] opened 2023-07-19 14:05 UTC
```
Register Repositories
Using github PAT from envvar GITHUB_PAT
Error: Error: Failed to install 'vise' from GitHub:
  SSL peer certificate or SSH remote key was not OK: [api.github.com] SSL: no alternative certificate subject name matches target host name 'api.github.com'
Execution halted
Error: Process completed with exit code 1.
```

See https://github.com/carpentries-incubator/bioc-intro/actions/runs/5600064601/jobs/10241911505

**Comment by zkamvar** [comment] 2023-07-19 14:25
I'm looking into this now.

**Comment by jdrnevich** [comment] 2023-07-19 14:35
@zkamvar I am getting what I think is similar error on the bioc-rnaseq site about "Failed to install 'varnish' from GitHub:" https://github.com/carpentries-incubator/bioc-rnaseq/actions/runs/5600313182. I successfully built the site just a couple of hours ago, and the pushed changes were minor edits.

**Comment by zkamvar** [comment] 2023-07-19 15:11
Thank you for the information, @jdrnevich. I believe it has something to do with GitHub's API given this error: `SSL peer certificate or SSH remote key was not OK: [api.github.com]` and other errors on subsequent runs accessing the carpentries universe that I cannot reproduce locally.

Seeing https://github.com/r-lib/remotes/issues/762#issuecomment-1594241715, and [the changes I just implemented](https://github.com/carpentries/actions/compare/e9405d9b8f2f99a2a7fd16a31194fd8563af95c9..3fb4f689d3fed641e2644e11ce3b312edc991c70), I believe it has to do with something that changed suddenly on GitHub's end, but this is something that is difficult for me to debug. I will continue to work on this and report back here when I find a solution.

**Comment by zkamvar** [comment] 2023-07-19 16:22
Apparently it's an ubuntu bug that will be fixed soon: https://fosstodon.org/@gaborcsardi/110741646942210567

I apologise to @lgatto because in my haste, I deleted the cache for this repo so that means the next build is going to install everything again once the bug is fixed 😓

**Comment by jdrnevich** [comment] 2023-07-19 16:28
Thanks @zkamvar for finding out what was going on! I'll just wait for the bug fix.

**Comment by zkamvar** [comment] 2023-07-20 13:52
@jdrnevich it looks like the builds are now succeeding: https://github.com/carpentries-incubator/bioc-rnaseq/actions/runs/5611246907/jobs/10267313448

@lgatto, I've restarted the build for this lesson, but because I clobbered the cache, it will probably take ~30 minutes or so.

**Comment by lgatto** [comment] 2023-07-20 15:33
Thank you!

**Closed** 2023-07-20 15:34 UTC
